version: 2
updates:
  # Configuration for Bun (using npm as a proxy)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0  # Prevents creating PRs
    versioning-strategy: auto
    ignore:
      # Ignore major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "bun"

  # Configuration for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0  # Prevents creating PRs
    ignore:
      # Ignore major updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "github-actions"